QCA_INCDIR = @QCA_INCLUDE_INSTALL_DIR@
QCA_LIBDIR = @QCA_LIBRARY_INSTALL_DIR@

CONFIG *= qt
INCLUDEPATH += $$QCA_INCDIR/QtCrypto
LIBS += -L$$QCA_LIBDIR

LINKAGE = -l@QCA_LIB_NAME@
CONFIG(debug, debug|release) {
	windows:LINKAGE = -l@QCA_LIB_NAME@d
	mac:LINKAGE = -l@QCA_LIB_NAME@_debug
}
LIBS += $$LINKAGE
