#!/bin/sh

if [ ! -f qca.pro ] || [ -d .svn ]; then
	echo This script should only be run within an exported qca tree.
	exit 1
fi

# remove cmake files
rm -rf cmake
rm crypto.prf.cmake
rm qca2.pc.cmake
find . -name CMakeLists.txt -exec rm {} \;
