<qconf>
 <name>Qt Cryptographic Architecture (QCA)</name>
 <profile>qca.pro</profile>
 <lib/>
 <incdir/>
 <libdir/>
 <datadir/>
 <moddir>qcm</moddir>
 <dep type='qt42'>
  <required/>
 </dep>
 <dep type='buildmode'>
  <required/>
 </dep>
 <dep type='buildmode_framework'>
  <required/>
 </dep>
 <dep type='universal'>
  <required/>
 </dep>
 <dep type='extra'>
  <required/>
 </dep>
 <dep type='certstore'>
  <required/>
 </dep>
</qconf>
