#!/bin/sh
export LD_LIBRARY_PATH="../../lib:$LD_LIBRARY_PATH"
cd base64unittest && make check && cd .. && \
cd bigintunittest && make check && cd .. && \
cd certunittest && make check && cd .. && \
cd cipherunittest && make check && cd .. && \
cd hashunittest && make check && cd .. && \
cd hexunittest && make check && cd .. && \
cd kdfunittest && make check && cd .. && \
cd keygenunittest && make check && cd .. && \
cd keylengthunittest && make check && cd .. && \
cd macunittest && make check && cd .. && \
cd pkits && make check && cd .. && \
cd securearrayunittest && make check && cd .. && \
cd staticunittest && make check && cd .. && \
cd symmetrickeyunittest && make check && cd .. && \
cd tls && make check && cd .. 
